### ISSUE TITLE
Can not abort loading / import in Cura

### ISSUE THREAD

**Issue by jKostet** [Ghostkeeper/SVGToolpathReader#13]
My svg takes forever to import. Issue may be in the svg itself (Inkscape svg), but there should be a X button to cancel import instead of having to close Cura.

**Comment by Ghostkeeper** [comment]
This is something that I cannot implement from a plug-in. Aborting the loading of a file would need to be implemented in Cura itself. Sorry!

The file likely takes long to import if it features long curves or if the Maximum Resolution setting is very small. Try increasing the setting value to 1mm or something. Curves are approximated by segments with the Maximum Resolution as length.
