### ISSUE TITLE
Request for Cura v5 Support

### ISSUE THREAD

**Issue by DivingDuck** [Ghostkeeper/SVGToolpathReader#15]
Hello Ghostkeeper
A kindly request for this plugin. It would be nice to have this plugin available for Cura v5 some when if times allows. 
Best regards,
DD

**Comment by Ghostkeeper** [comment]
This is (finally) fixed, in version 1.2.2.

**Comment by DivingDuck** [comment]
Thanks a lot.
FYI, I had problems with installing from the package. I choose the SVGToolpathReader1.2.2-sdk8.0.0.curapackage and nothing happen when I drag&drop the file in Cura 5.1.
I solved it by manually extracting the files from the zip file in the plugin folder.
Best regards, DD
