### ISSUE TITLE
Allow changing the XY size of the imported SVG

### ISSUE THREAD

**Issue by PhaserArray** [Ghostkeeper/SVGToolpathReader#17]
Currently the plugin will just ask for the desired Z height when importing an SVG. [The XY size seems to be set to fit it to the size of the entire printable area](https://github.com/Ghostkeeper/SVGToolpathReader/blob/deb2442b53be52d90f7cdf8bd7ffbeec1e187d0a/WriteGCode.py#L90-L93). Please add an option to define custom XY limits in the import pop up. It could just be a single percentage field that is applied to the max and min XY values.

**Comment by Ghostkeeper** [comment]
The X/Y size is not adjusted to the size of the printable area. It's simply the real size of the SVG image. If the SVG file specifies units, those are used. If not, one unit is interpreted as one mm, similar to how Cura interprets STL files (which also don't have units).
