### ISSUE TITLE
Installation instructions from source incomplete.

### ISSUE THREAD

**Issue by omdathetkan** [Ghostkeeper/SVGToolpathReader#5]
> From source: Download the latest source code from Github. In Cura, click on "Help", "Show configuration folder". Navigate to the "plugins" subfolder and unpack the .zip file from Github there. Rename the folder to "SVGToolpathReader" (removing any suffix that Github added such as "-master"). Restart Cura.

I think there is a step missing to generate a plugin.json file

**Comment by Ghostkeeper** [comment]
Yep, good catch. In fact, that's missing from all 3 of my published Cura plug-ins.
