### ISSUE TITLE
Travel Command is never skipped due to float precision

### ISSUE THREAD

**Issue by omdathetkan** [Ghostkeeper/SVGToolpathReader#6]
Currently travel commands are skipped as follows:

```
if command.x == x and command_y == y:
    continue  # Travel move wouldn't have any effect.
```

However due to rounding and precision this does not work as expected as you can see from this generated gcode snippet:
```
G1 X71.495625 Y41.394862 E0.125294
G1 X71.245918 Y42.362580 E0.136261
G0 F1500 E-6.363739 Z2.200000 (RETRACT)
G0 X71.245900 Y42.363000 F6000.000000
G0 F1500 E0.136261 Z0.200000 (UN-RETRACT)
G1 Y51.863000 F1200.000000 E0.240502
```

Current:
![image](https://user-images.githubusercontent.com/5098411/77691963-140ef400-6fa6-11ea-8d80-59818777458d.png)

Intended:
![image](https://user-images.githubusercontent.com/5098411/77691941-0bb6b900-6fa6-11ea-8c64-f9f901600dc0.png)

**Comment by Ghostkeeper** [comment]
This is fixed by your pull request. Thank you so much!
